
DROP TABLE IF EXISTS resources_tags CASCADE;
CREATE TABLE resources_tags (
  resource_id INTEGER PRIMARY KEY REFERENCES resources(id) NOT NULL,
  tag_id VARCHAR(255) PRIMARY KEY REFERENCES tags(id) NOT NULL
);
